# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0020_transform_bot_fields_to_big_integer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('government_score', models.IntegerField()),
                ('opposition_score', models.IntegerField()),
                ('motion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='tournament.Motion')),
            ],
        ),
    ]
