# Generated by Django 2.1.7 on 2019-04-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionanalysis',
            name='government_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='motionanalysis',
            name='opposition_score',
            field=models.IntegerField(default=0),
        ),
    ]
