# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_fix_username_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_registration_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
