# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_empty_user_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='motion',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
