# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_motion_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('chat_id', models.IntegerField(blank=True)),
                ('chat_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
