# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-23 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0019_feedbackanswer'),
    ]

    operations = [
        migrations.AlterField(model_name='botusers', name='chat_id', field=models.BigIntegerField(blank=True),),
        migrations.AlterField(model_name='botusers', name='user_id', field=models.BigIntegerField(),),
    ]
