from .defaults import *
from .database import *
from .allauth import *
from .smtp_email import *
from .static import *
from .telegram_bot import *
from .detact_language import *
from .debug import *
from .logging import *
